name: Java EE Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Find Java source files
      run: find payroll_back-master/src/java -name "*.java" > sources.txt
      
    - name: Filter Java source files
      run: cp sources.txt filtered_sources.txt
        
    - name: Install dependencies
      run: |
        mkdir lib
        curl -L -o lib/commons-io.jar https://repo1.maven.org/maven2/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
        curl -L -o lib/commons-logging-1.1.1.jar https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
        # Add more dependency downloads as needed
        
    - name: Create classes directory
      run: mkdir classes

    - name: Compile Java source files
      run: javac -d classes -classpath "lib/*" @filtered_sources.txt
      working-directory: payroll_back-master/src/java

    - name: Create WAR file
      run: jar -cvf your-web-app.war -C web .
