name: java-ee-build-pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt' # Specify the distribution (e.g., adopt, zulu)
          java-package: 'jdk'

      - name: Build with Ant
        run: ant build
        working-directory: payroll_back-master

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: payroll_back-master
          path: build/payroll_back-master.war

      - name: Create build directory
        run: mkdir -p build

      - name: Archive artifacts with commit ID
        if: success()
        run: |
         mv payroll_back-master.war build/payroll_back-master-$(git rev-parse --short HEAD).war
        shell: bash

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: payroll_back-master
          path: build/payroll_back-master-*.war


      # - name: Post-build actions (optional)
      #   # Add steps to deploy, run tests, etc. (use exit codes for error handling)
      #   run: |
      #     # Example: Deploy to a server
      #     scp my-java-ee-project.war user@server:deployments/
