name: Java EE Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt' # Specify the distribution (e.g., adopt, zulu)
        java-package: 'jdk'
      
    - name: Download Servlet API JAR
      run: |
        mkdir lib
        curl -o lib/servlet-api.jar https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar

    - name: Download JasperReports JAR
      run: |
       mkdir lib
       curl -o lib/jasperreports.jar https://repo1.maven.org/maven2/net/sf/jasperreports/jasperreports/6.17.0/jasperreports-6.17.0.jar

    - name: Download JSON Web Token JAR
      run: |
       curl -o lib/jsonwebtoken.jar https://repo1.maven.org/maven2/io/jsonwebtoken/jjwt/0.11.2/jjwt-0.11.2.jar


      
    - name: Build with Ant
      run: ant build
      working-directory: payroll_back-master

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-java-ee-project
        path: my-java-ee-project/my-java-ee-project.war
