name: Build and Upload Artifacts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

    - name: Build with Ant
      run: ant build

    - name: Create build directory
      run: mkdir -p build

    - name: Archive artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: payroll_back-master
        path: build/payroll_back-master.war

    - name: Report no files found
      if: failure() && steps.create_build_dir.outcome == 'success'
      run: echo "Warning:No files were found to upload."

    - name: Report build failure
      if: failure() && steps.create_build_dir.outcome != 'success'
      run: echo "Build failed:No build directory created."
