name: java-ee-build-pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use a suitable Java version for your application
          distribution: 'adopt'

      - name: Build with Ant
        run: ant build
        working-directory: payroll_back-master

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: payroll_back-master
          path: payroll_back-master/build/payroll_back-master.war

      - name: Use SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 4.213.119.32 >> ~/.ssh/known_hosts

      - name: Debug SSH Connection
        run: ssh -i ~/.ssh/id_rsa azureuser@4.213.119.32 "ls /var/lib/tomcat9/webapps/"

      - name: Copy Build Files to Server
        run: scp -r -i ~/.ssh/id_rsa dist/final_project_web/* azureuser@4.213.119.32:/var/lib/tomcat9/webapps/

      - name: Deploy to Server
        run: ssh -i ~/.ssh/id_rsa azureuser@4.213.119.32 "echo 'Hello from GitHub Actions!'"
