name: java-ee-build-pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use a suitable Java version for your application
          distribution: 'adopt'

      - name: Build with Ant
        run: ant build
        working-directory: payroll_back-master

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: payroll_back-master
          path: payroll_back-master/build/payroll_back-master.war

      - name: Stop Existing Java Process
        uses: appleboy/ssh-action@master
        with:
          host: 4.213.119.32
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop tomcat9

      - name: Debug SSH Key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Copy build files to server
        uses: appleboy/scp-action@v0.2.0
        with:
          host: 4.213.119.32
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "payroll_back-master/build/payroll_back-master.war"
          target: "/var/lib/tomcat9/webapps/"

      - name: Start New Java Process
        uses: appleboy/ssh-action@master
        with:
          host: 4.213.119.32
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl start tomcat9
