name: Java EE Build and Deploy

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Adjust the Java version if needed
        distribution: 'adopt'  # Specify the distribution, e.g., adopt, adopt-hotspot, adopt-openj9, etc.
        
    - name: Find Java source files
      run: find payroll_back-master/src/java -name "*.java" > sources.txt
      
    - name: Install dependencies
      run: |
        mkdir lib
        curl -L -o lib/commons-io.jar https://repo1.maven.org/maven2/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
        curl -L -o lib/commons-logging-1.1.1.jar https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
        curl -L -o lib/gson-2.3.1.jar https://repo1.maven.org/maven2/com/google/code/gson/gson/2.3.1/gson-2.3.1.jar
        curl -L -o lib/json_simple-1.1.jar https://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1/json-simple-1.1.jar
        curl -L -o lib/mysql-connector-java-8.0.15.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.15/mysql-connector-java-8.0.15.jar
        
    - name: Compile Java source files
       javac -d classes -classpath "lib/*:path/to/servlet-api.jar" @sources.txt


    - name: Create WAR file
      run: jar -cvf your-web-app.war -C web .
