name: Java EE Build and Deploy

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Adjust the Java version if needed
        distribution: 'adopt'  # Specify the distribution, e.g., adopt, adopt-hotspot, adopt-openj9, etc.
        
    - name: List Java source files
      run: ls -l payroll_back-master/src/java


    - name: Compile Java source files
      run: |
        javac -d classes -classpath "lib/*" payroll_back-master/src/java/controllers/*.java \
         payroll_back-master/src/java/dao/*.java \
         payroll_back-master/src/java/daoImpls/*.java \
         payroll_back-master/src/java/interfaces/*.java \
         payroll_back-master/src/java/models/*.java \
         payroll_back-master/src/java/threads/*.java \
         payroll_back-master/src/java/util/*.java




    - name: Create WAR file
      run: |
        jar -cvf your-web-app.war -C web .
